version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dobrofon_dev_bot
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
